name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from GitHub.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (Optional) Install Docker Compose (if not already available on the runner)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 3. (Optional) Pull the latest code and update configuration on the server.
      - name: Deploy to Oracle Cloud Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/justrooms-website
            git pull origin main
            # Stop and remove the current containers.
            docker-compose down
            # Pull prebuilt images from your registry.
            docker-compose pull
            # Start the containers in detached mode.
            docker-compose up -d
            docker-compose ps
