name: Build and Push Docker Images to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (required for multi-arch builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      # 4. Build and push Frontend image (multi-arch)
      - name: Build and push Frontend image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/justrooms-frontend:${{ github.sha }} \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/justrooms-frontend:latest \
            -f frontend/Dockerfile frontend --push

      # 5. Build and push Backend image (multi-arch)
      - name: Build and push Backend image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/justrooms-backend:${{ github.sha }} \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/justrooms-backend:latest \
            -f backend/Dockerfile backend --push
