name: Build and Push Docker Images to GHCR

# Trigger the workflow manually or on push to main (adjust as needed)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (optional but recommended for caching and multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_PAT }}

      # 4. Build and push Frontend image
      - name: Build and push Frontend image
        run: |
          # Build the image and tag it with the current commit SHA
          docker build -t ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-frontend:${{ github.sha }} -f frontend/Dockerfile frontend
          # Push the commit-specific tag
          docker push ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-frontend:${{ github.sha }}
          # Tag the image as "latest"
          docker tag ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-frontend:${{ github.sha }} ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-frontend:latest
          # Push the "latest" tag
          docker push ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-frontend:latest

      # 5. Build and push Backend image
      - name: Build and push Backend image
        run: |
          docker build -t ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-backend:${{ github.sha }} -f backend/Dockerfile backend
          docker push ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-backend:${{ github.sha }}
          docker tag ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-backend:${{ github.sha }} ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-backend:latest
          docker push ghcr.io/${{ secrets.GITHUB_USERNAME }}/justrooms-backend:latest
