name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images locally
        run: docker compose build

      - name: Deploy to Oracle Cloud Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Ensure the target directory exists
            cd /var/www
            mkdir -p justrooms-website
            cd justrooms-website
            # Pull the latest code (if you are using git on the server)
            git pull origin main
            # Stop current containers, pull prebuilt images, and start new containers
            docker compose down
            docker compose pull
            docker compose up -d
            docker compose ps
