name: Deploy to Oracle Cloud

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from GitHub.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (Optional) Build Docker images locally
      # This step runs on the CI runner; it ensures your Dockerfiles are valid.
      - name: Build Docker images locally
        run: docker-compose build

      # 3. Deploy to Oracle Cloud Server via SSH.
      - name: Deploy to Oracle Cloud Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Change to the deployment directory.
            cd /var/www/justrooms-website
            
            # Pull the latest changes from GitHub.
            git pull origin main
            
            # Stop and remove the old containers.
            docker-compose down
            
            # Rebuild and start containers in detached mode.
            docker-compose up -d --build
            
            # (Optional) List running containers to verify deployment.
            docker-compose ps
